language: node_js

cache:
  directories :
    - ~/.npm

node_js:
  - '13'

git:
  depth: 3

script:
  - yarn build

deploy:
  provider: pages
  edge: true
  skip-cleanup: true
  keep-history: true
  github-token: $Github_token
  local-dir: dist/
  target-branch: gh-pages
  commit_message: 'Deploy Successfully'
  on:
    branch: final
